action_id: trunk-share-with-everyone
date: 2024-11-16 08:19:33
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\9WlTa.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\9WlTa.yaml
timestamp: 1731745173
full_timestamp:
  nanos: 611231000
  seconds: 1731745173
trunk_version: 1.22.8
