action_id: trunk-share-with-everyone
date: 2024-11-17 17:49:44
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\hlO1S.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\hlO1S.yaml
timestamp: 1731865784
full_timestamp:
  nanos: 973734000
  seconds: 1731865784
trunk_version: 1.22.8
